### ISSUE TITLE
Add capnp files to VPR conda package and add target for making text versions of capnp files

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#1002]
https://github.com/SymbiFlow/symbiflow-arch-defs/pull/987 added two utilities for printing binary capnp files out to text for debugging.  There was a suggestion to add a target to invoke the tools, but this requires having the capnp schema's in symbiflow-arch-defs, which is not currently true.

Path forward is to:
 - Add capnp files to VPR conda package
 - Add CMake targets to generate text output from capnp binaries of the lookahead and place delay matrix files.

**Comment by mithro** [comment]
@acomodi

**Comment by litghost** [comment]
This has been fixed
