### ISSUE TITLE
bram_n7 test takes a lot of time and memory to route

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/symbiflow-arch-defs#1023]
bram_n7 test takes ~87 minutes to finish. See resource usage chart:

![resource_usage_top_bram_n7_bin](https://user-images.githubusercontent.com/3785621/65526259-1f973a80-def1-11e9-9831-c197d9f3488a.png)

bram_n8 takes ~23 minutes and this design is larger than bram_n7:

![resource_usage_top_bram_n8_bin](https://user-images.githubusercontent.com/3785621/65526587-a4825400-def1-11e9-93a9-e67ac1a5edc7.png)

This looks like a bug in VPR.

Also we may consider limiting bram tests to e.g. n3 to shorten the tests time.

**Comment by kgugala** [comment]
@litghost @mithro @acomodi

**Comment by litghost** [comment]
I believe https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1134 may resolve this issue.
