### ISSUE TITLE
lxml generates exception when writing more than 2 GB incrementally

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#1066]
There is a int32_t overflow bug in libxml2 (https://gitlab.gnome.org/GNOME/libxml2/issues/112) that causes an exception to be generated when more than 2 GB of XML is written.  The upstream maintainers have not merged a fix yet (see https://gitlab.gnome.org/GNOME/libxml2/merge_requests/54 or https://gitlab.gnome.org/GNOME/libxml2/merge_requests/55).  For now, libxml2 needs to be replaced.

Instructions:

1. Have symbiflow-arch-defs setup conda (e.g. `make all_conda`)
2. Clone `https://github.com/SymbiFlow/libxml2-feedstock` into a new directory
3. Execute the following commands:
```
export CONDA_DIR=<path to conda>
export PATH=$CONDA_DIR/bin:$PATH
# Make sure conda-build is installed in conda
conda install conda-build

# Build replacement package
cd <libxml2-feedstock directory>
conda-build .

# Install replacement package
conda install --use-local libxml2
```
If the conda environment is destroyed, the steps above will need to be repeated.

**Comment by litghost** [comment]
@mkurc-ant I'm working on creating a fork of https://github.com/conda-forge/libxml2-feedstock, I'll update the instruction once that is done and tested.

**Comment by litghost** [comment]
@mkurc-ant Try out the instructions.  If you want to test if the fix is working, the following script should run without error if the fix is in place: [repo_lxml.py.zip](https://github.com/SymbiFlow/symbiflow-arch-defs/files/3713720/repo_lxml.py.zip)

In order to run that script I usually run something like:
```
export CONDA_DIR=<path to conda>
export PATH=$CONDA_DIR/bin:$PATH
python3 -mpip install pandas
python3 -mpip install openpyxl
python3 repo_lxml.py
```

**Comment by mkurc-ant** [comment]
@litghost Thanks, It worked.
