### ISSUE TITLE
Reduce excessive memory usage of the XRay routing import

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1091]
1. Determine why the `prjxray_routing_import.py` uses ~20GB of memory when working on the full rr 50T graph
2. Optimize it to use less.

**Comment by mkurc-ant** [comment]
The `lib_rrgraph_xml` actually loads the whole XML (~950MB) to memory through the ElementTree (libxml) thus converting it into its internal representation. This is bad and very memory inefficient!

**Comment by mkurc-ant** [comment]
I'm working on a solution. So far I managed to reduce the memory footprint for the whole 50T graph to only a few GB by iteratively parsing the XML instead of loading it into memory at once.

**Comment by litghost** [comment]
> I'm working on a solution. So far I managed to reduce the memory footprint for the whole 50T graph to only a few GB by iteratively parsing the XML instead of loading it into memory at once.

Depending on how fast that solution ends up being, it may be worthwhile to think about using `xmllint` to filter the XML prior to even getting to the python.  It is unclear if `xmllint` can do iterative XML parsing + filtering.

**Comment by mkurc-ant** [comment]
Here it is: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1094
