### ISSUE TITLE
PLL and BUFG need to be placed in the same clock row region

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#1182]
There are several situations for which the clock is being routed from the PLL output to the BUFG tile that are placed in incompatible locations.

Incompatible location example:
- PLL placed in TOP half (e.g. X1Y1)
- BUFG placed in BOTTOM half (e.g. X0Y0).

In such a situation, nor the BUFG output can be driven to the PLL clk input neither PLL output to BUFG input.

This situation causes fasm2bels to fail, as well a non-working output bitstream produced with the symbiflow toolchain.

**Comment by acomodi** [comment]
@litghost FYI

**Comment by litghost** [comment]
I've proposed #1231 as a solution to this issue.

**Comment by acomodi** [comment]
Closing. Fixed with https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1237
