### ISSUE TITLE
Getting started build example

### ISSUE THREAD

**Issue by Tcub** [SymbiFlow/symbiflow-arch-defs#1188]
Hi,

I have just had a go at following the getting started instructions on the .io page. When running the make counter_arty_bin command it would fail and the traceback stated it could not find and import the numpy module while running prjxray_edge_library.py

I go it working by calling the pip install inside /build/env/conda/bin/ and installing numpy with it. I also noticed that pip is called to install numpy in one of the build files for the ice40 so I was wondering if maybe it was an oversight for xc7 devices. (It also could be a weird setup thing my end or classic not reading the instructions but I thought it worth mentioning)

**Comment by acomodi** [comment]
@Tcub To solve the issue without having to manually install numpy within conda, the following make target can be used:

```
make all_conda
```

I believe this should be added to the README

**Comment by Tcub** [comment]
Yep that worked. Many thanks for the help.

**Comment by acomodi** [comment]
Thanks for filing the issue. Closing.
