### ISSUE TITLE
Kokoro CI target "VtR + SymbiFlow Architecture Definitions" uses wrong VPR version

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1189]
I've observed some CI tests failing recently for a not obvious reason. I've also noticed that the Kokoro target "VtR + SymbiFlow Architecture Definitions (Presubmit)" uses the upstream VPR instead of the conda package pointed at by CMakeLists.txt file.

Is the use of upstream VPR intentional there?

**Comment by litghost** [comment]
I believe I see the issue, it is using master instead of master+wip.

**Comment by litghost** [comment]
@mithro

**Comment by litghost** [comment]
Issue has been resolved!

**Comment by mithro** [comment]
@litghost Have you confirmed Kokoro is now running on the right branch?

**Comment by litghost** [comment]
> @litghost Have you confirmed Kokoro is now running on the right branch?

Yes, https://source.cloud.google.com/results/invocations/154bb11d-4c63-413c-83de-7ab80fbaaeb2/details

**Comment by mithro** [comment]
Awesome!
