### ISSUE TITLE
Litex pending PRs

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#1198]
This issue collects all the pending PRs needed to build the full LiteX design.

### Necessary

These are the `necessary` PRs, critical for having a working HW implementation of the design:

- [x] IOBUF inference using Yosys: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1170
- [x] XDC Plugin integration: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1158
- [x] Mini Litex test (minimal version of the full LiteX design: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1181
- [x] LOC placement constraints: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1186
- [x] SERDES/IDELAY support: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1174
- [ ] HCLK_IOI support (for the IDELAYCTRL): https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1191

### PR not yet open

These is a collection of issues that still do not have an open PR:
- [ ] Support for various IOSTANDARDs and for IN_TERM and SLEW settings

### Not necessary

These are `not necessary` PRs, they do not directly impact the LiteX design build outcome:

- [ ] Minitest for different IOSTANDARDS: https://github.com/SymbiFlow/prjxray/pull/1157

**Comment by litghost** [comment]
Status's as of 12/4:
- IOBUF inference using Yosys: #1170
  - Needs to be rebase and updated now that Yosys fixes have been merged into Yosys master+wip
- XDC Plugin integration: #1158
  - Outstanding review comments
- Mini Litex test (minimal version of the full LiteX design: #1181
  - Pending behind #1158 
- LOC placement constraints: #1186
  - CI is red and pending review comments
- SERDES/IDELAY support: #1174
  - CI is red
- HCLK_IOI support (for the IDELAYCTRL): #1191
 - Outstanding review comments

**Comment by litghost** [comment]
Status as of 12/9:
- Mini Litex test (minimal version of the full LiteX design: #1181
 - Working on hardware, but needs LOC constraints to prevent BUFG and PLL from being placed in invalid locations.
- HCLK_IOI support (for the IDELAYCTRL): #1191
 - PR was split.  New PR is required to finish IDELAYCTRL support, as diff_fasm tests were failing and are currently disabled.

**Comment by acomodi** [comment]
This issue has been solved and LiteX is enabledand supported. Closing.
