### ISSUE TITLE
Refactor the Makefiles

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#12]
They are a pretty huge mess of stuff

**Comment by mithro** [comment]
Did some refactoring of the `Makefile.mux` files here -> https://github.com/mithro/symbiflow-arch-defs/blob/working-on-fasm/common/make/mux.mk

**Comment by mithro** [comment]
This is in progress here -> #56

**Comment by elmsfu** [comment]
Do you have more in find to refactor the makefiles?

**Comment by mithro** [comment]
I guess this is done!
