### ISSUE TITLE
genfasm excessive memory usage

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1225]
The genfasm uses surprisingly large amount of memory. For the `xc7/tests/counter` design it tops up at **11.5GB** for the full graph of xc7a50t device!

For the same design pack, place and route uses roughly about 6.5GB and that is probably due to the rr graph size.

**Comment by litghost** [comment]
This is a result of how rrgraph parsing and edge metadata is processed.  The uxsdcxx capnp parser uses far less memory.  There are also some changes to the metadata processing that will further lower memory usage.

**Comment by litghost** [comment]
I believe this has been resolved.
