### ISSUE TITLE
Make mux_gen.py satisfy pep8

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#13]
https://github.com/mithro/vpr-for-ice40/blob/master/utils/mux_gen.py

**Comment by Dhiraj240** [comment]
@mithro I want to do python related task before GSOC proposal submission.Please assign this to me or can i work on it ?

**Comment by elmsfu** [comment]
@Dhiraj240 I don't think we can assign it to you, but feel free to create a PR that addresses it.

**Comment by Dhiraj240** [comment]
@elmsfu are you maintainer of this project or GSOC student like me ? Alright i will make PR for it.

**Comment by elmsfu** [comment]
Closed in #508
