### ISSUE TITLE
Revisit icebox patch routing: index_pin_node_ids()

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/symbiflow-arch-defs#130]
In ice40_patch_routing_from_icebox.py I added a map named name_rr2local in index_pin_node_ids() that converts between icebox and symbiflow naming. Recently someone (@jhol IIRC) did some cleanup to make symbiflow names match icebox a lot closer. This mapping should be revised to see if it can be simplified or completely removed.

@mithro notes there may be some issues representing / in VPR names. So its possible we might still end up with a / to _ translation.

**Comment by mithro** [comment]
This is fixed by https://github.com/SymbiFlow/symbiflow-arch-defs/pull/150.
