### ISSUE TITLE
Investigate weird routing in ice40 arch

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#131]
Taking a look at this picture there are two weird things;
![image](https://user-images.githubusercontent.com/21212/40578133-9e27250c-60c3-11e8-9f63-29a50fc42ffa.png)

The output pin of this BLK_TL-PLB seems to be connected to a span12 in an adjacent column. Highlighted below;
![image](https://user-images.githubusercontent.com/21212/40578140-c64e8386-60c3-11e8-8906-201b6479974f.png)

The local tracks seem to be connected to an adjacent column.
Highlighted below;
![image](https://user-images.githubusercontent.com/21212/40578152-1ae7db40-60c4-11e8-8f92-b4bede95b864.png)

**Comment by mcmasterg** [comment]
To be clear, this ticket is about concerns over the routing fabric, not the routing on the fabric?

Your main concerns are that the spans are not located closer to what they are connecting? Do you believe this is wrong based on some documentation? Or just find it suspicious that they aren't adjacent?

**Comment by mithro** [comment]
Why are these connected to columns adjacent? It seems suspicious.

**Comment by mithro** [comment]
This seems to be fixed by https://github.com/SymbiFlow/symbiflow-arch-defs/pull/150
