### ISSUE TITLE
Make xml_deps.py satsify pep8

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#14]
https://github.com/mithro/vpr-for-ice40/blob/master/utils/xml_deps.py

**Comment by Cabalist** [comment]
This file no longer exists.  :)  Also `deps_xml.py` looks pretty good PEP8-wise.

**Comment by mithro** [comment]
It has changed to [deps_xml as you mentioned](https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/utils/deps_xml.py).

If you think the file is all good, I guess we can close this issue?

**Comment by Cabalist** [comment]
The only issue my linter throws is the "continuation indent" as referenced in #13.

**Comment by Dhiraj240** [comment]
In reference to #13  please assign this also to me.Can i work on it ?

**Comment by elmsfu** [comment]
@Dhiraj240 Feel free to work on this and create a PR. You can mention the issue ID in the PR description.

**Comment by Dhiraj240** [comment]
Alright :+1:

**Comment by Dhiraj240** [comment]
@elmsfu Please close this issue it is already satisfying pep8.

**Comment by elmsfu** [comment]
`yapf` has no issues with this file.
