### ISSUE TITLE
Add an cmake option to disable a200t installtion

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/symbiflow-arch-defs#1405]
Currently it is disabled in the code. Let's make it configurable

**Comment by HackerFoo** [comment]
Can we just enable this now, or should there be a way to select which architectures to install?

If so, can we instead have a `install_${arch}` target for each architecture? That would allow generating separate packages.

**Comment by litghost** [comment]
I believe this issue can be closed?

**Comment by kgugala** [comment]
yep
