### ISSUE TITLE
Add support for MMCM

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1468]
Xilinx 7-series FPGAs have PLLs (PLLE2_ADV) and MMCMs (MMCME2_ADV). Both have the same function though MMCMs have some additional features.

Currently SymbiFlow has support only for PLLs. Adding support for MMCMs would require duplicating and augmenting what's done for PLLs. All bits for MMCMs should be known but it has to be double- checked.

**Comment by litghost** [comment]
PR opened for unknown bits: https://github.com/SymbiFlow/prjxray/pull/1447

arch-def side of this is still needed.

**Comment by mkurc-ant** [comment]
A WIP PR to arch-defs: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1729

**Comment by mkurc-ant** [comment]
https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1729 has been merged. Closing
