### ISSUE TITLE
VPR prunes IDELAYCTRL during netlist optimization

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1470]
This happens as in the regular use case an IDELAYCTRL has only input pins connected which makes VPR treat it as a block with no relevance to the circuit operation. There is the RDY output which can be connected to something to prevent that but that is merely a workaround.

**Comment by mkurc-ant** [comment]
Idea 1 - Upgrade VPR so it can have special annotations on `model`/`pb_type` which informs it that should neven be pruned.

Idea 2 (may be a separate thing) - Make VPR understand netlist cell attributes like "KEEP".

**Comment by litghost** [comment]
@acomodi I believe this has been fixed?

**Comment by acomodi** [comment]
Yes, this has been fixed on VPR upstream, closing.
