### ISSUE TITLE
Add support for IO constraints in XDC format

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1471]
Currently there is only support for PCF format. That requires conversion XDC -> PCF for each new design (ported from vendor tools). XDC is essentially a TCL script so support for it can be added to the `prjxray_create_ioplace.py` script by taking advantage of a TCL parsing library and implementing relevant commands in it.

**Comment by litghost** [comment]
@tmichalak I believe can close this issue?

**Comment by tmichalak** [comment]
The plugin and arch-defs related changes have been merged. Closing.
