### ISSUE TITLE
Support multiple synth IO tiles at the same vpr coordinate

### ISSUE THREAD

**Issue by andrewb1999** [SymbiFlow/symbiflow-arch-defs#1550]
For custom harnesses and partition regions, there should be the ability to place multiple synth IO tiles at the same VPR coordinate, connecting to different wires at the border of the ROI.

I think this can be implemented relatively easily using by increasing the tile capacity, but I am unsure how to handle an INPAD and and OUTPAD at the same vpr coordinate.  My initial thought is to merge these together into an SYN-IOPAD and maybe have the INPAD and OUTPAD as equivalent sites.

**Comment by andrewb1999** [comment]
@litghost Can you let me know your thoughts?

**Comment by litghost** [comment]
So @acomodi add the feature to support this, which is heterogeneous tiles.  There are documentation and examples upstream.  I'll find a link.

**Comment by litghost** [comment]
Link to doc: https://docs.verilogtorouting.org/en/latest/tutorials/arch/heterogeneous_tiles/#heterogeneous-tiles-tutorial
