### ISSUE TITLE
Move to use XDC instead of tcl constraints during fasm2bels

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#1576]
This is a follow up to https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1545.

XDC-based constraints should ulteriorly speed-up the vivado step in the fasm2bels pipeline, as currently, sourcing the TCL has been verified to be the bottleneck of the entire process.

**Comment by litghost** [comment]
This is done?  Can be closed, yes?

**Comment by acomodi** [comment]
Yes, closing.
