### ISSUE TITLE
[xc7] Ambiguous fasm features for ISERDES

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#1589]
Current set of fasm features for the `ISERDES` primitive does not allow to unambiguously decode the de-serialization factor (DATA_WIDTH). For example the data width of 4 and 6 cannot be distinguished.

Solving this would require making some adjustments to the fuzzer.

**Comment by litghost** [comment]
@mkurc-ant I believe you've fixed this issue?

**Comment by mkurc-ant** [comment]
@litghost Yes, this is fixed.
