### ISSUE TITLE
Use external fasm2bels library

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#1596]
https://github.com/SymbiFlow/symbiflow-xc-fasm2bels has been extracted from symbiflow-arch-defs to be used as a standalone tool.

As part of the extraction effort, we would need to transition and use the external library within arch-defs, so that it gets tested in CI and also it does prevent us from increasing the work required in maintaining two versions of the same library

**Comment by litghost** [comment]
This has been completed
