### ISSUE TITLE
Integrate yosys params plugin

### ISSUE THREAD

**Issue by tmichalak** [SymbiFlow/symbiflow-arch-defs#1621]
Yosys' setparam and getparam (implemented in the [params plugin](https://github.com/SymbiFlow/yosys-symbiflow-plugins/pull/26)) commands should be used in the arch-defs synth.tcl script to recalculate the parameters before techmapping of the PLL blocks, e.g the CLKOUT%n_PHASE should be multiplied by 1000 in order for the final eblif have the correct values of parameters.

**Comment by litghost** [comment]
@tmichalak Can this issue be closed?

**Comment by tmichalak** [comment]
PR has been merged. Closing.
