### ISSUE TITLE
Generated FASM files get appended to existing ones

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#1656]
In case build files for a specific test are already present, and another build is performed, the `top.merged.fasm`, which is used to generate the bitstream, is not overwritten, but instead, the new fasm data of the second build gets appended. This obviously causes FASM collisions when generating the frames.

The problematic lines are the following: https://github.com/SymbiFlow/symbiflow-arch-defs/blob/b3864ae63d668fc7d321b94ca946841e80dd0bb6/common/cmake/devices.cmake#L1058-L1073

Could be solved by removing the `arch.merged.fasm` file if present, before running the FASM files merge procedure.

@andrewb1999 I believe this was an addition for the partial regions, therefore we have multiple FASM files that need to be collapsed in one only for the bitsream generation step. Do you think the above solution is valid and does not break the partial regions stuff?

**Comment by andrewb1999** [comment]
Yes, this change was made for partial regions work.  Removing the merged.fasm if it exists should work fine.
