### ISSUE TITLE
Remove `VTR + symbiflow-arch-defs` step from arch-defs builds

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#1783]
There has been some confusion on the differences between the arch-defs kokoro and Travis CI's and the `VTR master+wip + arch-defs` kokoro CI.  The `VTR master+wip + arch-defs` CI should only really show up on the Symbiflow/VTR repo.

**Comment by mithro** [comment]
This one -> `VtR + SymbiFlow Architecture Definitions (Presubmit) — Build failed` and https://source.cloud.google.com/results/invocations/26544b67-b8d8-4cad-b472-2673730dcbe7/targets ?

**Comment by litghost** [comment]
@mithro has made the changes to support this, and tested it.
