### ISSUE TITLE
Split rr_graph generation and patching from the test running

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#182]
Currently the rr_graph generation and patching steps are down as part of running a test.

It would be nicer if this was a totally separate process.

**Comment by litghost** [comment]
The CMake system separates the rr_graph generation and patching (see add_device target https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/make/devices.cmake#L307) from the particular FPGA target.  All FPGA targets that use the same device will leverage the same rr_graph output.
