### ISSUE TITLE
Kokoro running out of memory

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/symbiflow-arch-defs#1884]
Tests are failing on Kokoro with:

```
virtual memory exhausted: Cannot allocate memory
```

e.g. https://source.cloud.google.com/results/invocations/c40e6db8-e047-466f-87c4-483eb97d6429/targets/foss-fpga-tools%2Fsymbiflow-arch-defs%2Fpresubmit%2Fdocs/log

**Comment by litghost** [comment]
> Tests are failing on Kokoro with:
> 
> ```
> virtual memory exhausted: Cannot allocate memory
> ```
> 
> e.g. https://source.cloud.google.com/results/invocations/c40e6db8-e047-466f-87c4-483eb97d6429/targets/foss-fpga-tools%2Fsymbiflow-arch-defs%2Fpresubmit%2Fdocs/log

Why did you file an issue that is a result of a change in your own PR in #1880 ?

**Comment by HackerFoo** [comment]
It only fails on some of the builds, so it appears to be a CI issue.

**Comment by litghost** [comment]
> It only fails on some of the builds, so it appears to be a CI issue.

Those VM machine are smaller, but the issue is that you added building of ANTLR4 to jobs like the `docs` jobs, etc.  Again, this issue arose in your PR only, so I'm not sure why you've filled an issue.
