### ISSUE TITLE
Profile the ice40_import_routing_from_icebox script and make it fast

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#192]
The current [`ice40_import_routing_from_icebox.py`](ice40/utils/ice40_import_routing_from_icebox.py) takes a long time to run. Currently the script is written to make it easy to understand and debug the rr_graph. There is plenty of room for optimization and making it fast!

Someone should profile it and make it fast!

**Comment by elmsfu** [comment]
Duplicate of #196
