### ISSUE TITLE
Makefile fails in confusing way if Make version 3.82 is used.

### ISSUE THREAD

**Issue by galv** [SymbiFlow/symbiflow-arch-defs#197]
I noticed this while trying to run this on an RHEL7 machine. Workaround is to install Make 4.1, which is available in devtoolset-6. I can probably document this myself and add an error message if the Make version is too old. Making this issue as a reminder to myself.

```
$ make env
Discovered makefiles:
make/gen.mk:5: *** No configs found for mux.  Stop.
```

**Comment by mithro** [comment]
@galv Thanks for reporting this! I think this would be a great temporary fix.

Our current make system is a bit of a monstrosity and we are hoping to replace it with something simpler (probably lead by @elmsfu) -- see #101. If you have experience in this area, I'm sure he would love some help. The tricky part is the chaining of generation and dealing with dependencies.
