### ISSUE TITLE
Had anyone tried to make it supporting two kinds of iopads ？

### ISSUE THREAD

**Issue by the-centry** [SymbiFlow/symbiflow-arch-defs#2047]
Is there some solution to make symbiflow supporting two kinds of iopad?

**Comment by mithro** [comment]
I'm not sure what you mean by this?

We already support all the types of iopads needed for DDR memory and other things...

**Comment by the-centry** [comment]
> ry and other thin

How to support IOB33 and IOB18? If I want to use IOB18 and IOB33 at the same time in a design,how to diff the two kinds of iopads when yosys and vpr deal the design?
Thanks so much!
