### ISSUE TITLE
Wrong in generate rr_graph.real.patched.bin

### ISSUE THREAD

**Issue by szhou888** [SymbiFlow/symbiflow-arch-defs#2309]
while generating rr_graph.real.patched.bin,wrong happened as these:

`**num_edges:303245222**

Traceback (most recent call last):
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/xc/common/utils/prjxray_routing_import.py", line 1428, in <module>
    main()
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/xc/common/utils/prjxray_routing_import.py", line 1414, in main
    node_remap=node_remap,
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/utils/lib/rr_graph_capnp/graph2.py", line 566, in serialize_to_capnp
    self._write_edges(rr_graph, num_edges, edges_obj, node_remap)
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/utils/lib/rr_graph_capnp/graph2.py", line 433, in _write_edges
    out_edges = rr_graph.rrEdges.init('edges', num_edges)
  File "capnp/lib/capnp.pyx", line 1271, in capnp.lib.capnp._DynamicStructBuilder.init
  File "capnp/lib/capnp.pyx", line 1289, in capnp.lib.capnp._DynamicStructBuilder.init
capnp.lib.capnp.KjException: capnp/layout.c++:1212: failed: total size of struct list is larger than max segment size
stack: 7fcb71ddda79 7fcb71e1374e 7fcb71e138e6 7fcb71d090fa 7fcb71c8f25e 55c903f08913 55c903f08a30 55c903f74ebc 55c903f07e7a 55c903f7073f 55c903eb7828 55c903f08106 55c903f71584 55c903f07e7a 55c903f704b5 55c903eb7828 55c903eb8713 55c903eb873b 55c903fcff13 55c903fda330 55c903fda522 55c903fdb654 55c903fdb77b 7fcb73aefbf6 55c903f7ffef
`

The source code is:
`    **def _write_edges(self, rr_graph, num_edges, edges, node_remap):**

        """ Serialize list of edge tuples objects to capnp.

        edge tuples are (src_node(int), sink_node(int), switch_id(int), metadata(NodeMetadata)).

        metadata may be None.

        Note that this method is extremely hot, len(edges) **is order 5-50 million**.
        Almost any modification of this function has a significant effect on
        performance, so any modification to this function should be tested for
        performance and correctness before commiting.

        """
        print("num_edges:{}".format(num_edges))
        out_edges = rr_graph.rrEdges.init('edges', num_edges)

        edges_written = 0
        edges_iter = iter(edges)
        for out_edge, (src_node, sink_node, switch_id,
                       metadata) in zip(out_edges, edges_iter):
            edges_written += 1
            out_edge.srcNode = node_remap(src_node)
            out_edge.sinkNode = node_remap(sink_node)
            out_edge.switchId = switch_id

            if metadata is not None and len(metadata) > 0:
                metas = out_edge.metadata.init('metas', len(metadata))
                for out_meta, (name, value) in zip(metas, metadata):
                    out_meta.name = name
                    out_meta.value = value

        assert edges_written == num_edges, 'Unwritten edges!'

        try:
            _ = next(edges_iter)
            assert False, 'Unwritten edges!'
        except StopIteration:
            pass`
If someone has way to solve problem like this?
Thanks so much!

**Comment by the-centry** [comment]
Maybe this code [constexpr uint SEGMENT_WORD_COUNT_BITS = 29;      // Number of words in a segment.](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/common.h) could tell you why.
