### ISSUE TITLE
Fix timing based packing for 7-series

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#286]
Some blocks in the current packing graph result in invalid timing paths that cause the clusterer to explode.  This is likely as simple as fixing broken timing paths and removing constant source from routing graph (see #285).

**Comment by litghost** [comment]
Timing based packing is currently **disabled** via the options " --place_algorithm bounding_box --enable_timing_computations off".  Removing these options from https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/xc7/artix7.cmake#L69 will turn timing based packing back on.

When timing based packing is on, VPR crashes because outputs from the TIEOFF block have no clock.  This is actually correct, because these outputs are constants.  However the current use of TIEOFF is incorrect, and should be refactored to solve #285.

**Comment by kgugala** [comment]
I re-enabled timing packing and vpr does not crash. Enabling that did not fix #284

**Comment by litghost** [comment]
Double check that the arguments are present with make VERBOSE=1, sometimes the CMake variable cache gets in the way.

**Comment by kgugala** [comment]
I double checked this. Timing based placing is enabled.
