### ISSUE TITLE
Refine FASM support in VPR

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#288]
Currently FASM support in VPR was written to target 7-series only.  Effectively no tests have been written for the FASM in VPR support.

Tasks:

- Add unit testing for FASM support
- Integrate ice40 FASM output

**Comment by litghost** [comment]
@elmsfu is working on integrating ice40 FASM output

**Comment by elmsfu** [comment]
#447 addresses the ice40 FASM output and FASM -> Bit.

**Comment by elmsfu** [comment]
Splitting issue into the two separate tasks.
