### ISSUE TITLE
Add Travis-CI support for 7-series

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#290]
Currently the RAM usage for the 7-series workflow is too large for Travis-CI.  Refactor the 7-series routing import logic to avoid using more than 4 GB of RAM.

**Comment by litghost** [comment]
I believe the routing import can now be performed on travis, we should add rr graph generation for 7-series back to travis, combined with some parallelism to bring the runtime in check.

**Comment by litghost** [comment]
Turns out the bigger problem is the 50 minute time limit on travis, and we are already close to that with current runs taking ~38 minutes.

**Comment by mithro** [comment]
You can have multiple runs at the same time - see https://github.com/SymbiFlow/prjxray/blob/master/.travis.yml#L21-L34 for example.

If we can split this into ice40, testarch and xc7 would it be fast enough?

**Comment by litghost** [comment]
> You can have multiple runs at the same time - see https://github.com/SymbiFlow/prjxray/blob/master/.travis.yml#L21-L34 for example.
> 
> If we can split this into ice40, testarch and xc7 would it be fast enough?
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/34549754?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[SymbiFlow/prjxray](https://github.com/SymbiFlow/prjxray)**Documenting the Xilinx 7-series bit-stream format. - SymbiFlow/prjxray

Potentially, and problably valuable anyways to cut down on CI time.  Probably worth attacking splitting the arches first, then add xc7 as a follow up.  I've thought about having explicit arch support flags, and this would be a good outgrowth of that idea.

**Comment by litghost** [comment]
With kokoro CI running, this is obsolete.
