### ISSUE TITLE
Add Arty to the artix7/boards.cmake file 

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#307]
As one of our primary development platforms it would be good to add the Arty to https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/artix7/boards.cmake

**Comment by YungBae3** [comment]
Awsome have to try

**Comment by litghost** [comment]
Before this is fixed, #298 should be fixed.

**Comment by elmsfu** [comment]
@acomodi Should this be closed with #462?

**Comment by acomodi** [comment]
@elmsfu Yes, I believe we can close this issue

**Comment by elmsfu** [comment]
Fixed by #462
