### ISSUE TITLE
basys3 counter example does not build

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/symbiflow-arch-defs#311]
It fails with:

```
Error 1: 
Type: Blif file
File: symbiflow-arch-defs/build/artix7/tests/counter/counter/artix7-xc7a50t-roi-virt-xc7a50t-test/top.eblif
Line: 12
Message: Failed to find matching architecture model for 'CYINIT_CONSTANTS'
```

**Comment by kgugala** [comment]
I added the `CYINIT_CONSTANT` models from https://github.com/litghost/symbiflow-arch-defs/tree/artix7_startup/artix7/primitives/slicel

now the build fails with `Failed to find matching architecture model for 'FDRE'`

**Comment by kgugala** [comment]
the `FDRE` issue is caused by too old yosys version downloaded by conda. Building with current SymbiFlow/yosys master does not generate this error

**Comment by litghost** [comment]
Ya, those errors are caused by an old yosys techmap.  #294 was created to move some of the tech mapping definitions from yosys to symbiflow to mitigate this issue somewhat.

**Comment by litghost** [comment]
I think tim kicked off a conda package rebuild with https://github.com/SymbiFlow/conda-packages/commit/5f02998f8cbf24bffa5564fe7f34f07ccf0749ea so hopefully this fixes itself.

**Comment by litghost** [comment]
FYI, until #294 is resolved, I recommend setting the env var YOSYS to point to a local yosys executable.

**Comment by mithro** [comment]
I believe the Yosys in conda should be up to date now. Can someone please
check if it works?

**Comment by kgugala** [comment]
Yosys from conda is now correct.
