### ISSUE TITLE
INPUT_IO_FILES issues in add_fpga_target_boards

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#346]
The cmake function add_fpga_target_boards in make/devices.cmake has an issue when explicitly stating the `INPUT_IO_FILES`. It has to further checked. More information in this PR https://github.com/SymbiFlow/symbiflow-arch-defs/pull/333#issuecomment-459014079

**Comment by litghost** [comment]
This has been fixed.
