### ISSUE TITLE
Remove use of design.bit (ROI bitstream harness)

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#418]
Once ready, eliminate use of design.bit for making output bitstreams.

Prerequisites:
- [x] https://github.com/SymbiFlow/prjxray/issues/684
- [x] https://github.com/SymbiFlow/prjxray/issues/694

Tasks:
- [x] Modify harness generation to output all bits outside of ROI and add them to "required_features" in the design.json
- [x] Use tool from https://github.com/SymbiFlow/prjxray/issues/694 to create bitstream from frames, rather than patching design.bit with xc7patch.

**Comment by tmichalak** [comment]
The PR for the last task is ready #500, however it's blocked by https://github.com/SymbiFlow/prjxray/issues/746
