### ISSUE TITLE
vtr from conda does not recognize --round_robin_prepacking option

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/symbiflow-arch-defs#427]
this option has been added by the https://github.com/SymbiFlow/symbiflow-arch-defs/commit/60700b81aa5221ea99c72100aa26c3e67adb28b3 commit.

The option is implemented in vtr. We just need to bump the conda package

**Comment by kgugala** [comment]
also genfasm should be updated:
```

Unexpected command-line argument '--round_robin_prepacking'

usage: genfasm architecture circuit [--pack] [--place] [--route] 
       [--analysis] [--disp {on, off}] [-h] [--version] [--device DEVICE_NAME] 
       [-j NUM_WORKERS] [--timing_analysis {on, off}] 
       [--route_chan_width CHANNEL_WIDTH] [OTHER_OPTIONS ...]

```

**Comment by mithro** [comment]
@kgugala Why would the `--round_robin_prepacking` be passed to the `genfasm` command?

**Comment by kgugala** [comment]
this is because all the vtr tools share the same arguments. The arguments are defined here: https://github.com/SymbiFlow/symbiflow-arch-defs/blob/master/xc7/make/arch_define.cmake#L27

**Comment by mithro** [comment]
To rebuild vpr follow https://github.com/SymbiFlow/conda-packages/pull/10
