### ISSUE TITLE
RAMB36 not implemented

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#438]
To have picosoc running the program data is saved in BRAMs. To allow it to correctly compile right now the bram yosys techlibs (`brams.txt`) has to be updated as follows:

```
#match $__XILINX_RAMB36_SDP
#  min bits 4096
#  min efficiency 5
#  shuffle_enable B
#  make_transp
#  or_next_if_better
#endmatch

match $__XILINX_RAMB18_SDP
  min bits 4096
  min efficiency 5
  shuffle_enable B
  make_transp
  or_next_if_better
endmatch

#match $__XILINX_RAMB36_TDP
#  min bits 4096
#  min efficiency 5
#  shuffle_enable B
#  make_transp
#  or_next_if_better
#endmatch

match $__XILINX_RAMB18_TDP
  min bits 4096
  min efficiency 5
  shuffle_enable B
  make_transp
endmatch
```

This is to exclude RAMB36

**Comment by litghost** [comment]
Disabling RAMB36 inference is a good short term solution, but we should enable RAMB36 place and route in symbiflow-arch-defs as well.

**Comment by acomodi** [comment]
Agreed. For now, when compiling picosoc yosys has to be overriden with the local version that has RAMB36 disabled.

**Comment by litghost** [comment]
Closing this issue and tracking in #902
