### ISSUE TITLE
Create build target for to run python tests

### ISSUE THREAD

**Issue by elmsfu** [SymbiFlow/symbiflow-arch-defs#481]
Currently existing python tests are not run. There should be a top level target to run all python tests.

Travis script should then call that target.

This can be addressed after #463

**Comment by elmsfu** [comment]
Looks like we have an attempt to support `pytest`, but previously I think we had `doctest` running. More recently we have used `unittest`.

The target should run `unittest` and `doctest`. If we use `pytest` we should phase them out in favor of `unittest`

**Comment by mithro** [comment]
@elmsfu pytest is a "test runner". It runs [`unittest`](https://docs.pytest.org/en/latest/unittest.html) and [`doctest`](https://docs.pytest.org/en/latest/doctest.html) tests.

We should continue to use `unittest` and `doctest` but use pytest as the test runner when running everything at once.

**Comment by elmsfu** [comment]
Fixed by #520

**Comment by mithro** [comment]
Yay! \o/
