### ISSUE TITLE
missing tbassert.v?

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/symbiflow-arch-defs#593]
During CMake build env creartion `deps_verilog` throws the following error:

```
deps_verilog.py: error: argument inputfile: can't open 'symbiflow-arch-defs/library/tbassert.v': [Errno 2] No such file or directory: 'symbiflow-arch-defs/library/tbassert.v'
```

This does not seem to be critical as it does not break the build process.

**Comment by litghost** [comment]
This is fixed in master after 71670ab
