### ISSUE TITLE
Add tests for sim.v

### ISSUE THREAD

**Issue by elmsfu** [SymbiFlow/symbiflow-arch-defs#598]
Yes, cocotb is no longer a dependency we support without significant effort.  We should find another approach to testing sim.v files.

_Originally posted by @litghost in https://github.com/SymbiFlow/symbiflow-arch-defs/pull/586_

Previously we had some support for testing using cocotb. That package has had some recent development and may be more easily leveraged. We should also consider other approaches.

**Comment by litghost** [comment]
I think this issue is duplicated from https://github.com/SymbiFlow/symbiflow-arch-defs/issues/59

**Comment by elmsfu** [comment]
Yep, didn't realize that was still open.
