### ISSUE TITLE
Make the "Generated dependency info XXXX.dmk" not have absolute paths

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#67]
Currently when a dependency file is created it outputs the following message;
 `Generated dependency info /home/travis/build/mithro/symbiflow-arch-defs/.deps//vpr/ff/vpr_ff.model.xml.dmk`.

It would be good if these messages didn't have the absolute path in them.

**Comment by mithro** [comment]
Example image;
![image](https://user-images.githubusercontent.com/21212/37111381-5ecd63b6-21f4-11e8-828b-864813846ed5.png)

**Comment by elmsfu** [comment]
@mithro I'm not seeing this. Did you already fix it with #56 ?
