### ISSUE TITLE
Make the dependency generated messages colorful

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#68]
Currently when a dependency file is created it outputs the following message with no colors;
 `Generated dependency info /home/travis/build/mithro/symbiflow-arch-defs/.deps//vpr/ff/vpr_ff.model.xml.dmk`.

It would be good if these messages were colorful like the other build messages. See image below;
![image](https://user-images.githubusercontent.com/21212/37111467-9970eb3c-21f4-11e8-8a82-5ef59358b10e.png)

**Comment by mithro** [comment]
@bushig has a pull request for working on this here -> https://github.com/SymbiFlow/symbiflow-arch-defs/pull/83

**Comment by litghost** [comment]
Obsolete
