### ISSUE TITLE
template being synthesized instead of ignored

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/symbiflow-arch-defs#86]
How to reproduce:
`symbiflow-arch-defs/artix7$ make`

Example output: `symbiflow-arch-
defs/artix7/primitives/slicel/carry4/carry4_split/carry4_Nmux/ntemplate.carry4_Nmux.sim.v:8: syntax error, unexpected '{', expecting ';' or '#' or '('`
Noting file has: `module CARRY4_{N}MUX(CI, DI, S, O);`

**Comment by elmsfu** [comment]
I couldn't reproduce with master. Also it looks like you are on an older revision as [carry4](https://github.com/SymbiFlow/symbiflow-arch-defs/tree/master/artix7/primitives/slicel/carry4_modes) was renamed.

**Comment by mithro** [comment]
I believe that @JohnDMcMaster just had left over files in this repo.
