### ISSUE TITLE
Investigate high channel width on test

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/symbiflow-arch-defs#88]
Re: "make ARCH=testarch DEVICE=2x4 mlut.echo"
I ran some rr_graph tests and noticed the test is choosing a channel width of 28. This seems a bit high, but I'm not that familiar with this configuration to know if its actually unreasonably or not given this is a relatively small device. Investigate the test and understand why such a high channel width was used

arch-defs: 8929d23
vpr: 8.0.0-dev+vpr-7.0.5-5759-gc4b24af1f

**Comment by JohnDMcMaster** [comment]
We are actively investigating some related arch.xml results we don't understand with the VPR devs. Hopefully this will also resolve this ticket

**Comment by mithro** [comment]
I believe this has been fixed.
