### ISSUE TITLE
[xc7/fasm2v] Add support for IDELAY

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#909]
fasm2v needs support for IDELAY BEL's. Minitest should be created first per https://github.com/SymbiFlow/prjxray/issues/998.

Support for IDELAY + ISERDES is the priority.

**Comment by mkurc-ant** [comment]
A note for supporting IDELAY in VPR: Each clock region has a IDELAYCTRL bel required for calibrating IDELAYs. There is one IDELAYCTRL per clock region. Using an IDELAY must be associated with instancing a correct IDELAYCTRL (from the same clock region).

See https://www.xilinx.com/support/documentation/user_guides/ug471_7Series_SelectIO.pdf page 126.
