### ISSUE TITLE
[xc7/fasm2v] Crash when parsing tags like DATA_WIDTH.8

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#920]
The textX library used for parsing FASM files crashes when it encounters a tak in a format:
`ISERDES.DATA_WIDTH.8`

The problem is that after `.` we have an identifier that starts from a number instead of a letter.

Possible solutions:

- Do not use tags that start from a number.
- Fix the FASM file parser to allow for `[0-9a-zA-Z]` as identifier.

**Comment by litghost** [comment]
> * Do not use tags that start from a number.

I've fixed the ISERDES tags, and the latest DB no longer emits ".8".  See https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/segbits_lioi3.db#L61
