### ISSUE TITLE
[xc7/fasm2v] Crash on assertion has_feature('PULLTYPE.PULLDOWN')

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#925]
With the database from `g50b9a02` the fasm2bels crashes on assertion when expecting the tag `PULLTYPE.PULLDOWN` to be set on an IOB.

This tag is defined as an all-zero tag so it will never show up in FASM disassembly.

Suggested solutions:
- Remove the assertion
- Invert the tag in the fuzzer so we would have `PULLTYPE.ZPULLDOWN`

**Comment by litghost** [comment]
@mkurc-ant This is fixed, yes?

**Comment by mkurc-ant** [comment]
@litghost Yep, it's fixed. And actually `PULLTYPE.PULLDOWN` does show in fasm disassembly.
