### ISSUE TITLE
[xc7/fasm2v] Support multiple iostandards in one design

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#927]
Currently there is a need to specify only one iostandard for the whole design. Also the encoding of iostandards as FASM features is pretty ambiguous (but maybe it has to be that way due to bit encoding).

**Comment by litghost** [comment]
It appears there are several IOSTANDARD combinations that do not have distinct bits.  We may have to supply the original IOSTANDARD's used per port for fasm2v.

**Comment by mkurc-ant** [comment]
Fixed by https://github.com/SymbiFlow/symbiflow-arch-defs/pull/938
