### ISSUE TITLE
[xc7/fasm2v] Add support for more tile types

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/symbiflow-arch-defs#928]
Those are not supported right now (maybe not only them):

- [LR]IOI3
- [LR]IOI3_SING
- [LR]IOI3_TBYTESRC
- [LR]IOI3_TBYTETERM
- HCLK_IOI3

**Comment by litghost** [comment]
I'd rather have issues for particular black boxes (e.g. #909) than via tile type.
