### ISSUE TITLE
SRL32 missing timing

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/symbiflow-arch-defs#958]
https://github.com/SymbiFlow/symbiflow-arch-defs/blob/93541beb621030a30506312e86583ddcae5c327b/xc7/primitives/slicem/srl/srlc32e_vpr.pb_type.xml#L9

Timing values look like dummy values.

**Comment by mkurc-ant** [comment]
Yep, they are dummy

**Comment by mkurc-ant** [comment]
I started defining those timings and stumbled upon an issue. The SRL has output O6 which is sequentially related to inputs DI1,CE and combinationaly related to address input A. Like in the picture below:

![TimingForVPR - LogicInp2](https://user-images.githubusercontent.com/47315577/63522328-66f86880-c4f8-11e9-8b47-07c46ae4e528.png)

Unfortunatelly such a structure is not supported by the VPR timing model. Supported structures are only those: http://docs.verilogtorouting.org/en/latest/tutorials/arch/timing_modeling/#arch-model-timing-tutorial

**Comment by mkurc-ant** [comment]
https://github.com/SymbiFlow/symbiflow-arch-defs/pull/959

**Comment by litghost** [comment]
Can this be closed?

**Comment by mkurc-ant** [comment]
@litghost Yep.
